# Generated by Django 4.0.4 on 2022-06-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_paciente_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='texto',
            field=models.TextField(verbose_name='Observações'),
        ),
    ]
