# Generated by Django 4.0.4 on 2022-06-24 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psicologo',
            name='filiacao',
        ),
    ]
