# Generated by Django 4.0.4 on 2022-06-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='data_nasc',
            field=models.DateField(verbose_name='Data de nascimento (ano-mês-dia)'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='filiacao',
            field=models.CharField(max_length=100, verbose_name='Filiação'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='matricula',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
