# Generated by Django 4.0.4 on 2022-06-16 18:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_cadastro_data_nasc_alter_cadastro_filiacao_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cadastro',
            new_name='CadastroAluno',
        ),
    ]
