# Generated by Django 4.0.4 on 2022-06-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CRP', models.CharField(max_length=10)),
                ('matricula', models.CharField(max_length=15)),
                ('data', models.DateTimeField(verbose_name='Data da consulta')),
                ('horario', models.TimeField(verbose_name='Horário da consulta')),
            ],
        ),
    ]
