# Generated by Django 4.0.4 on 2022-06-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_alter_consulta_crp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='CRP',
            field=models.CharField(max_length=15),
        ),
    ]
