# Generated by Django 4.0.4 on 2022-06-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_alter_consulta_crp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateField(verbose_name='Data da consulta'),
        ),
    ]
