# Generated by Django 4.0.4 on 2022-07-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0005_alter_consulta_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateTimeField(verbose_name='Data da consulta'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='matricula',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
